// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHooLO0GWMGWVNhSrDNIDQutNS1Jwcgs0',
    appId: '1:609699828202:web:23e85017a0724aa957e293',
    messagingSenderId: '609699828202',
    projectId: 'fluttersignin-af057',
    authDomain: 'fluttersignin-af057.firebaseapp.com',
    storageBucket: 'fluttersignin-af057.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoJUJ4RQcAYV_51eisi2j_rqfof7xAA8',
    appId: '1:609699828202:android:36942466e48410b457e293',
    messagingSenderId: '609699828202',
    projectId: 'fluttersignin-af057',
    storageBucket: 'fluttersignin-af057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7rXRQEcQuwXBXqoQkIAXLcjVXQzY--c',
    appId: '1:609699828202:ios:ae65fc311c195a5757e293',
    messagingSenderId: '609699828202',
    projectId: 'fluttersignin-af057',
    storageBucket: 'fluttersignin-af057.appspot.com',
    iosBundleId: 'com.example.testforkotlinversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7rXRQEcQuwXBXqoQkIAXLcjVXQzY--c',
    appId: '1:609699828202:ios:ae65fc311c195a5757e293',
    messagingSenderId: '609699828202',
    projectId: 'fluttersignin-af057',
    storageBucket: 'fluttersignin-af057.appspot.com',
    iosBundleId: 'com.example.testforkotlinversion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHooLO0GWMGWVNhSrDNIDQutNS1Jwcgs0',
    appId: '1:609699828202:web:62534def8a4bcf5957e293',
    messagingSenderId: '609699828202',
    projectId: 'fluttersignin-af057',
    authDomain: 'fluttersignin-af057.firebaseapp.com',
    storageBucket: 'fluttersignin-af057.appspot.com',
  );

}